//Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"M fikri",
    "email":"amin@gmail.com",
    "password":"123456",
    "confPassword":"123456",
    "role":"admin"
}
###
//get All Users 

GET http://localhost:5000/users
